<div class="loadingio-spinner-dual-ball-hesm5mtw3zn">
	<div class="ldio-k6ch370tpm">
		<div></div>
		<div></div>
		<div></div>
	</div>
</div>

<style type="text/css">
	@keyframes ldio-k6ch370tpm-o {
		0% {
			opacity: 1;
			transform: translate(0 0);
		}
		49.99% {
			opacity: 1;
			transform: translate(61.6px, 0);
		}
		50% {
			opacity: 0;
			transform: translate(61.6px, 0);
		}
		100% {
			opacity: 0;
			transform: translate(0, 0);
		}
	}
	@keyframes ldio-k6ch370tpm {
		0% {
			transform: translate(0, 0);
		}
		50% {
			transform: translate(61.6px, 0);
		}
		100% {
			transform: translate(0, 0);
		}
	}
	.ldio-k6ch370tpm div {
		position: absolute;
		width: 61.6px;
		height: 61.6px;
		border-radius: 50%;
		top: 46.2px;
		left: 15.4px;
	}
	.ldio-k6ch370tpm div:nth-child(1) {
		background: #f43f5e;
		animation: ldio-k6ch370tpm 1.1764705882352942s linear infinite;
		animation-delay: -0.5882352941176471s;
	}
	.ldio-k6ch370tpm div:nth-child(2) {
		background: #404040;
		animation: ldio-k6ch370tpm 1.1764705882352942s linear infinite;
		animation-delay: 0s;
	}
	.ldio-k6ch370tpm div:nth-child(3) {
		background: #f43f5e;
		animation: ldio-k6ch370tpm-o 1.1764705882352942s linear infinite;
		animation-delay: -0.5882352941176471s;
	}
	.loadingio-spinner-dual-ball-hesm5mtw3zn {
		width: 154px;
		height: 154px;
		display: inline-block;
		overflow: hidden;
		background: none;
	}
	.ldio-k6ch370tpm {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-k6ch370tpm div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>
