<div class="loadingio-spinner-ellipsis-v7hr0cqtt9c">
	<div class="ldio-f7mqo2sdzfv">
		<div></div>
		<div></div>
		<div></div>
		<div></div>
		<div></div>
	</div>
</div>

<style type="text/css">
	@keyframes ldio-f7mqo2sdzfv {
		0% {
			transform: translate(12px, 80px) scale(0);
		}
		25% {
			transform: translate(12px, 80px) scale(0);
		}
		50% {
			transform: translate(12px, 80px) scale(1);
		}
		75% {
			transform: translate(80px, 80px) scale(1);
		}
		100% {
			transform: translate(148px, 80px) scale(1);
		}
	}
	@keyframes ldio-f7mqo2sdzfv-r {
		0% {
			transform: translate(148px, 80px) scale(1);
		}
		100% {
			transform: translate(148px, 80px) scale(0);
		}
	}
	@keyframes ldio-f7mqo2sdzfv-c {
		0% {
			background: #f43f5e;
		}
		25% {
			background: #404040;
		}
		50% {
			background: #f43f5e;
		}
		75% {
			background: #404040;
		}
		100% {
			background: #f43f5e;
		}
	}
	.ldio-f7mqo2sdzfv div {
		position: absolute;
		width: 40px;
		height: 40px;
		border-radius: 50%;
		transform: translate(80px, 80px) scale(1);
		background: #f43f5e;
		animation: ldio-f7mqo2sdzfv 1s infinite cubic-bezier(0, 0.5, 0.5, 1);
	}
	.ldio-f7mqo2sdzfv div:nth-child(1) {
		background: #404040;
		transform: translate(148px, 80px) scale(1);
		animation:
			ldio-f7mqo2sdzfv-r 0.25s infinite cubic-bezier(0, 0.5, 0.5, 1),
			ldio-f7mqo2sdzfv-c 1s infinite step-start;
	}
	.ldio-f7mqo2sdzfv div:nth-child(2) {
		animation-delay: -0.25s;
		background: #f43f5e;
	}
	.ldio-f7mqo2sdzfv div:nth-child(3) {
		animation-delay: -0.5s;
		background: #404040;
	}
	.ldio-f7mqo2sdzfv div:nth-child(4) {
		animation-delay: -0.75s;
		background: #f43f5e;
	}
	.ldio-f7mqo2sdzfv div:nth-child(5) {
		animation-delay: -1s;
		background: #404040;
	}
	.loadingio-spinner-ellipsis-v7hr0cqtt9c {
		width: 200px;
		height: 200px;
		display: inline-block;
		overflow: hidden;
		background: none;
	}
	.ldio-f7mqo2sdzfv {
		width: 100%;
		height: 100%;
		position: relative;
		transform: translateZ(0) scale(1);
		backface-visibility: hidden;
		transform-origin: 0 0; /* see note above */
	}
	.ldio-f7mqo2sdzfv div {
		box-sizing: content-box;
	}
	/* generated by https://loading.io/ */
</style>
